// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CrackTheCodeController from "./crack_the_code_controller"
application.register("crack-the-code", CrackTheCodeController)

import CrossSiteAnimationsController from "./cross_site_animations_controller"
application.register("cross-site-animations", CrossSiteAnimationsController)

import DisableButtonController from "./disable_button_controller"
application.register("disable-button", DisableButtonController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RotateDialController from "./rotate_dial_controller"
application.register("rotate-dial", RotateDialController)
