// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CrackTheCodeController from "./crack_the_code_controller"
application.register("crack-the-code", CrackTheCodeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
